nome = str(input('seu nome completo : '))
print('analisando seu nome...')
print('seu nome em minusculas  é: {} ' .format(nome.lower()))
print('seu nome em maiusculas é: {} ' .format(nome.upper()))
print('seu nome ao todo tem {} letras ' .format(len(nome) - nome.count(' ')))
separa = nome.split()
print('seu primeiro nome é {} e ele tem {} letras  '.format(separa [0],len(separa[0])))