n = str(input('digite seu nome completo : ')).strip()
nome = n.split()
#print(nome[0])
print('seu primeiro nome é {}'.format(nome[0]))
print('muito prazer em te conhecer :)')
#print('seu primeiro nome é {}'.format(nome[0]))
print('seu ultimo nome é: {}'.format(nome[len(nome)-1]))