n1 = float(input('Digite o primeiro valor: '))
n2 = float(input('Digite o segumdo valor: '))
n3 = float(input('Digite o terceiro valor: '))
soma_dobro = (n1 * 2) + (n2 * 2) + (n3 * 2)
print('a soma do DOBRO dos números digitados é igual a {:.2f}'.format(soma_dobro))